# Generated by Django 4.2.4 on 2024-04-18 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvedoresFavoritos',
            fields=[
                ('id_fProvedores', models.AutoField(primary_key=True, serialize=False)),
                ('provedor', models.ForeignKey(db_column='provedor_id', on_delete=django.db.models.deletion.CASCADE, to='api.provedores')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
